# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: cocherbusiness
services:
  - name: product-api
    project: src/Services/Product/Monbsoft.CocherBusiness.Product.Api/Monbsoft.CocherBusiness.Product.Api.csproj
  - name: cocher-data
    image: mongo
    bindings:
      - port: 27017
        connectionString: "mongodb://${host}:${port}"
